import { TASK_FREQUENCIES } from './constants'

export function calculateROI(tasks, automationPercent, implementationCost) {
  const pct = automationPercent / 100

  const taskBreakdown = tasks.map((task) => {
    const freq = TASK_FREQUENCIES.find((f) => f.label === task.frequency)
    const annualWeeks = 52
    const annualHours = task.hoursPerWeek * annualWeeks
    const annualCost = annualHours * task.hourlyCost
    const hoursSaved = annualHours * pct
    const costSaved = annualCost * pct

    return {
      ...task,
      annualHours,
      annualCost,
      hoursSaved: Math.round(hoursSaved),
      costSaved: Math.round(costSaved),
      automatedHours: Math.round(annualHours - hoursSaved),
      automatedCost: Math.round(annualCost - costSaved),
    }
  })

  const totalAnnualHours = taskBreakdown.reduce((sum, t) => sum + t.annualHours, 0)
  const totalAnnualCost = taskBreakdown.reduce((sum, t) => sum + t.annualCost, 0)
  const totalHoursSaved = taskBreakdown.reduce((sum, t) => sum + t.hoursSaved, 0)
  const totalCostSaved = taskBreakdown.reduce((sum, t) => sum + t.costSaved, 0)

  const netSavingsYear1 = totalCostSaved - implementationCost
  const roiPercent = implementationCost > 0
    ? Math.round((netSavingsYear1 / implementationCost) * 100)
    : 0

  const paybackMonths = totalCostSaved > 0
    ? Math.round((implementationCost / (totalCostSaved / 12)) * 10) / 10
    : 0

  const fiveYearSavings = totalCostSaved * 5 - implementationCost

  // Monthly projection data for charts
  const monthlyProjection = []
  let cumulativeSavings = -implementationCost
  for (let month = 0; month <= 24; month++) {
    cumulativeSavings += month === 0 ? 0 : totalCostSaved / 12
    monthlyProjection.push({
      month: `M${month}`,
      savings: Math.round(cumulativeSavings),
      investment: implementationCost,
      monthlySavings: Math.round(totalCostSaved / 12),
    })
  }

  return {
    taskBreakdown,
    totalAnnualHours,
    totalAnnualCost,
    totalHoursSaved,
    totalCostSaved,
    netSavingsYear1,
    roiPercent,
    paybackMonths,
    fiveYearSavings,
    implementationCost,
    automationPercent,
    monthlyProjection,
    hoursSavedPerWeek: Math.round(totalHoursSaved / 52),
    daysFreedPerYear: Math.round(totalHoursSaved / 8),
  }
}

export function formatCurrency(value) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value)
}

export function formatNumber(value) {
  return new Intl.NumberFormat('en-US').format(value)
}

export function generateReportText(results, businessInfo) {
  const lines = [
    '═══════════════════════════════════════════════════',
    '         AI AUTOMATION ROI REPORT',
    '         Generated by Skynet Labs',
    '         www.skynetjoe.com',
    '═══════════════════════════════════════════════════',
    '',
    `Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    '',
    '── BUSINESS INFORMATION ──────────────────────────',
    `Industry:      ${businessInfo.industry}`,
    `Company Size:  ${businessInfo.companySize}`,
    `Current Tools: ${businessInfo.currentTools}`,
    '',
    '── AUTOMATION SETTINGS ──────────────────────────',
    `Automation Level:     ${results.automationPercent}%`,
    `Implementation Cost:  ${formatCurrency(results.implementationCost)}`,
    '',
    '── KEY RESULTS ──────────────────────────────────',
    `Annual Time Saved:    ${formatNumber(results.totalHoursSaved)} hours`,
    `Annual Cost Savings:  ${formatCurrency(results.totalCostSaved)}`,
    `ROI:                  ${results.roiPercent}%`,
    `Payback Period:       ${results.paybackMonths} months`,
    `Net Year 1 Savings:   ${formatCurrency(results.netSavingsYear1)}`,
    `5-Year Total Savings: ${formatCurrency(results.fiveYearSavings)}`,
    `Hours Freed/Week:     ${results.hoursSavedPerWeek}`,
    `Work Days Freed/Year: ${results.daysFreedPerYear}`,
    '',
    '── TASK BREAKDOWN ──────────────────────────────',
  ]

  results.taskBreakdown.forEach((task, i) => {
    lines.push(``)
    lines.push(`  ${i + 1}. ${task.name}`)
    lines.push(`     Hours/Week: ${task.hoursPerWeek} | Rate: $${task.hourlyCost}/hr`)
    lines.push(`     Annual Cost: ${formatCurrency(task.annualCost)}`)
    lines.push(`     Savings:     ${formatCurrency(task.costSaved)} (${formatNumber(task.hoursSaved)} hrs)`)
  })

  lines.push('')
  lines.push('── BEFORE vs AFTER ──────────────────────────────')
  lines.push(`  Before Automation:  ${formatNumber(results.totalAnnualHours)} hrs/yr | ${formatCurrency(results.totalAnnualCost)}/yr`)
  lines.push(`  After Automation:   ${formatNumber(results.totalAnnualHours - results.totalHoursSaved)} hrs/yr | ${formatCurrency(results.totalAnnualCost - results.totalCostSaved)}/yr`)
  lines.push('')
  lines.push('═══════════════════════════════════════════════════')
  lines.push('  Ready to implement AI automation?')
  lines.push('  Book a FREE consultation at www.skynetjoe.com')
  lines.push('═══════════════════════════════════════════════════')

  return lines.join('\n')
}
